CurveTemplate/Controllers/DefaultSliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurveTemplate.Controllers
{
    public class DefaultSliderController : Controller
    {
        //
        // GET: /DefaultSlider/

        public ActionResult Home()
        {
            return PartialView();
        }

    }
}

CurveTemplate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurveTemplate.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CurveTemplate/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="post">
    <h1>@ViewBag.Title.</h1>
    <h2>Curve inspired template for ASP.NET MVC4 projects</h2>
</hgroup>

<section class="post">
    <header>
        <h3>About this template</h3>
    </header>
    <p>
        This template was inspired by the Curve template from <a href="http://chocotemplates.com/corporate/curve/">chocotemplates.com</a>. Their description is below.
    </p>
    <p>Free CSS template perfectly optimized for tablets and mobile phones. Curve is a creative website template that will suit a wide range of uses such as business, personal and portfolio websites. We have tested the responsive template on all major web browsers (IE, Firefox, Opera, Safari, Chrome) Moreover, we made sure that the responsive template works good on tablets and mobile devices based on iOs, Android and Windows Mobile. So, go ahead and download our free responsive template now! Just don’t remove the backlink to our website in order to stick with the free license.
    </p>
</section>
<section class="post">
    <header>
        <h3>Template Features</h3>
    </header>
    <ul>
        <li>jQuery carousel</li>
        <li>Responsive layout for tablets and mobile devices</li>
        <li>Properly commented code</li>
        <li>Valid HTML3/CSS3 markup</li>
        <li>Tested on PC, Mac, and mobile devices</li>
    </ul>
</section>
<hr style="clear:both" />

CurveTemplate/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="post">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="post">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="post">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="post">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

CurveTemplate/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section slider {
    @{ Html.RenderAction("Home", "DefaultSlider");}
}

<a href="#" class="m-btn-grey grey-btn">request a demo.</a>
<section class="cols">
    <div class="col">
        <img src="~/content/images/col-img1.png" alt="" />
        <div class="col-cnt">
            <h2>Design</h2>
            <p>
                Lorem ipsum dolor sit amet, con-<br />
                sectetur adipiscing dolor emor
            </p>
            <a href="#" class="more">view more</a>
        </div>
    </div>
    <div class="col">
        <img src="~/content/images/col-img2.png" alt="" />
        <div class="col-cnt">
            <h2>Branding</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing dolor</p>
            <a href="#" class="more">view more</a>
        </div>
    </div>
    <div class="col">
        <img src="~/content/images/col-img3.png" alt="" />
        <div class="col-cnt">
            <h2>Development</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing dolor</p>
            <a href="#" class="more">view more</a>
        </div>
    </div>
    <div class="cl">&nbsp;</div>
</section>
<section class="post">
    <div class="video-holder">
        <img src="~/content/images/video-img.png" alt="" />
    </div>

    <div class="post-cnt">
        <h2>What’s in the box?</h2>
        <p><strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit adispicing amet</strong> Cras molestie condimentum consequat. Nam leo libero, scelerisque tincidunt amet nsectetur adipiscing elit. Cras molestie condimentum nsectetur adipiscing elit. Cras molestie condimentum consequat pretium donec dictum mattis elit, nec:</p>

        <ul>
            <li><a href="#">jQuery Fader</a></li>
            <li><a href="#">Various column options</a></li>
            <li><a href="#">Valid XHTML and CSS tableless Design</a></li>
            <li><a href="#">Tested on Mac &amp; PC</a></li>
        </ul>
    </div>
    <div class="cl">&nbsp;</div>
</section>

<section class="testimonial">
    <h2>Responsive CSS Template with jQuery Fader</h2>

    <p><strong class="quote">“</strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consequat. Nam leo libero, scelerisque tincidunt commodo id, hendrerit vitae orci. Suspendisse eget nibh turpis. Sed at accumsan neque. Praesent purus eros, egestas eu tempus ut, mollis et libero”</p>

    <p class="author">John Doe, <strong>Company Name</strong></p>
</section>